// FinanceFlow · smoke test · S24 · T2 taxonomie v admin Mapě položek (taxonomie.js + admin.js)
const fs=require('fs'),path=require('path'),vm=require('vm');
const najdi=(...c)=>c.map(p=>path.join(__dirname,p)).find(p=>fs.existsSync(p));
const R=(...c)=>fs.readFileSync(najdi(...c),'utf8');
const ctx={console,window:{},fetch:async()=>({ok:false})};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(R('helpers.js','../js/helpers.js'),ctx);
vm.runInContext(R('taxonomie.js','../js/taxonomie.js'),ctx);
const T=JSON.parse(R('taxonomie.json','../data/taxonomie.json'));
let ok=0,bad=0;const t=(n,c,i)=>{c?ok++:(bad++,console.log('❌',n,i===undefined?'':JSON.stringify(i)));};
t('bez načtení nic nespadne',ctx.taxNavrh('mleko')===null&&ctx.taxHledej('ml').length===0&&ctx.taxInfo('x')===null);
const idx=ctx.taxNastav(T);
t('index má všechny názvy',Object.keys(idx).length>=900,Object.keys(idx).length);
const j=ctx.taxInfo('jogurt');
t('jogurt → podkategorie a oblast',j&&j.podId==='jogurty'&&j.oblastId==='potraviny'&&j.coicop==='01.146');
t('výjimka COICOP u názvu',ctx.taxInfo('máslo').coicop==='01.152'&&ctx.taxInfo('máslo').podId==='smetana');
t('rozpočet z oblasti',ctx.taxInfo('pivo').rozpocet==='cat26');
t('info i podle textu s diakritikou',ctx.taxInfo('Polotučné mléko').id==='polotucne mleko');
const N=(x)=>{const r=ctx.taxNavrh(x);return r?r.info.nazev+'|'+r.jistota:null;};
t('přesná shoda',N('MLÉKO')==='mléko|presne');
t('delší název vyhrává',N('Mléko polotučné 1l')==='polotučné mléko|slova',N('Mléko polotučné 1l'));
t('zkratka z pokladny',N('JOG OVOC 150')==='ovocný jogurt|zkratka',N('JOG OVOC 150'));
t('jednoslovná zkratka pokrytá z poloviny',N('JOGU')==='jogurt|zkratka',N('JOGU'));
t('příliš krátká zkratka nic',N('SAL')===null,N('SAL'));
t('nesmysl nic',N('XYZ QWE')===null);
t('gramáž nevadí',N('ROHLÍK 43G')==='rohlík|presne');
t('hledání: začátek názvu první',ctx.taxHledej('jog')[0].nazev==='jogurt');
t('hledání podle podkategorie',ctx.taxHledej('drůbeží').some(z=>z.nazev==='kuřecí prsa'));
const m=ctx.taxDoMapy(ctx.taxInfo('kuřecí prsa'));
t('záznam mapy z taxonomie',m.obecnyId==='kureci prsa'&&m.obecny==='kuřecí prsa'&&m.catId==='cat1'&&m.coicop===1);
t('obecnyId projde pravidlem',/^[a-z0-9 ]{1,60}$/.test(m.obecnyId));
t('všechna id projdou pravidlem',Object.keys(idx).every(k=>/^[a-z0-9 ]{1,60}$/.test(k)),Object.keys(idx).find(k=>!/^[a-z0-9 ]{1,60}$/.test(k)));
t('obecny ≤ 40 znaků',Object.values(idx).every(z=>ctx.taxDoMapy(z).obecny.length<=40));
// admin
const A=R('admin.js','../js/admin.js');
const cut=n=>{let a=A.indexOf('function '+n+'(');let i=A.indexOf('{',a),d=0;for(;i<A.length;i++){if(A[i]==='{')d++;else if(A[i]==='}'){d--;if(!d)break;}}return A.slice(a,i+1);};
['mapaAdminFiltruj','mapaMigraceNavrh','mapaAdminRadek'].forEach(n=>vm.runInContext(cut(n),ctx));
vm.runInContext(A.match(/const _vzEsc = [^\n]+/)[0].replace('const ','var ')+';'+A.match(/const _jsEsc = [^\n]+/)[0].replace('const ','var ')+';'+A.match(/const _onEsc = [^\n]+/)[0].replace('const ','var '),ctx);
ctx.S={categories:[{id:'cat1',name:'Jídlo & Nákupy',icon:'🛒'}]};
const items=[{itemKey:'jog ovoc',tagList:[{tag:'mlecne',cnt:2}]},{itemKey:'rohlik',tagList:[{tag:'pecivo',cnt:1}]},{itemKey:'x<y',tagList:[{tag:"a'<b>",cnt:1}]}];
const zaz={'rohlik':{obecny:'rohlík',obecnyId:'rohlik'},'jog ovoc':{obecny:'mléčné'}};
t('filtr bez taxonomie',ctx.mapaAdminFiltruj(items,zaz,{stav:'bez',q:''}).length===2);
t('filtr hotové',ctx.mapaAdminFiltruj(items,zaz,{stav:'hotove',q:''})[0].itemKey==='rohlik');
t('hledání podle podkategorie',ctx.mapaAdminFiltruj(items,zaz,{stav:'vse',q:'pečivo'}).some(i=>i.itemKey==='rohlik'));
const mig=ctx.mapaMigraceNavrh({'jog ovoc':{obecny:'mléčné'},'rohlik':{obecny:'rohlík',obecnyId:'rohlik'},'brambory rane':{obecny:'zelenina',konkretni:'brambory'},'zzz':{obecny:'qqq'}});
t('migrace: hotové přeskočí',!mig.some(x=>x.klic==='rohlik'));
t('migrace: konkrétní název',mig.find(x=>x.klic==='brambory rane').info.nazev==='brambory');
t('migrace: zkratka',mig.find(x=>x.klic==='jog ovoc').info.nazev==='ovocný jogurt');
t('migrace: nespárované zůstane',mig.find(x=>x.klic==='zzz').info===null);
vm.runInContext('var _mapaZaznamy='+JSON.stringify(zaz),ctx);
const h1=ctx.mapaAdminRadek(items[1]); t('řádek: řetěz taxonomie',h1.includes('Pečivo')&&h1.includes('COICOP 01.113')&&h1.includes('Jídlo'));
const h0=ctx.mapaAdminRadek(items[0]); t('řádek: návrh ze zkratky',h0.includes('💡 Návrh: ovocný jogurt'));
const h2=ctx.mapaAdminRadek(items[2]); t('řádek: escapování',!h2.includes('<b>')&&!h2.includes('x<y'));
console.log(`\n${ok} OK, ${bad} chyb`); if(bad) process.exitCode=1;
